name: mrdc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - boto3
  - pandas
  - PyYAML
  - requests
  - SQLAlchemy
  - streamlit
  - pip
  - pip:
    - tabula_py
    - psycopg2
    - python-dotenv